apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend-service
  name: frontend-service
spec:
  ports:
    - name: "8080"
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: frontend