spring:
  jpa:
    database-platform: org.hibernate.dialect.h2.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console